# Generated by Django 2.2.23 on 2021-09-23 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colour', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
